# Generated by Django 2.2 on 2019-05-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0002_auto_20190520_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='account_type',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
