# Generated by Django 2.2 on 2019-05-23 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0005_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_id', models.IntegerField()),
                ('point', models.IntegerField()),
                ('title', models.TextField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.TimeField()),
            ],
        ),
    ]
