# Generated by Django 2.2 on 2019-05-23 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0006_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
