# Generated by Django 2.2 on 2019-05-24 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_admin', '0007_auto_20190523_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='posts',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
